services:

  apache:
    image: httpd
    container_name: apache 
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    restart: unless-stopped

  nginx-proxy:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx-proxy 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: acme
# Uncomment the next two lines to use ZeroSSL instead of Let's Encrypt certs
#    environment:
#      - ACME_CA_URI=https://acme.zerossl.com/v2/DV90
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: unless-stopped

volumes:
  certs:
