services:

  gittea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__SERVER__DOMAIN=${DOMAIN}
      - GITEA__SERVER__SSH_DOMAIN=${DOMAIN}
      - GITEA__SERVER__ROOT_URL=https://${DOMAIN}/
      - GITEA__SERVICE__DISABLE_REGISTRATION=${DISABLE_REGISTRATION}
      - GITEA__MANUAL__CONFIRM=${REGISTER_MANUAL_CONFIRM}
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    restart: always
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"

  nginx-proxy:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx-proxy 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: acme
# Uncomment the next two lines to use ZeroSSL instead of Let's Encrypt certs
#    environment:
#      - ACME_CA_URI=https://acme.zerossl.com/v2/DV90
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: unless-stopped

volumes:
  certs:
